# Site Settings
title: Jekyll particles template
description: >
  My Jekyll template from blank with custom css and particles background.
baseurl: ''
url: 'https://test.richardpordan.com/'
sass:
  sass_dir: _sass
include: ['_pages', '_posts']
