# Site Settings
title: Jekyll particles template
description: >
  My Jekyll template from blank with custom css and particles background.
baseurl: ''
url: 'http://localhost:4000'
sass:
  sass_dir: _sass
include: ['_pages', '_posts']
